namespace Aimp4.Api
{
    public enum AIMPFileInfoPropId
    {
        Custom = 0,
        Album = 1,
        AlbumArt = 2,
        AlbumArtist = 3,
        AlbumGain = 4,
        AlbumPeak = 5,
        Artist = 6,
        BitRate = 7,
        Bpm = 8,
        Channels = 9,
        Comment = 10,
        Composer = 11,
        Copyright = 12,
        CueSheet = 13,
        Date = 14,
        DiskNumber = 15,
        DiskTotal = 16,
        Duration = 17,
        FileName = 18,
        FileSize = 19,
        Genre = 20,
        Lyrics = 21,
        Mark = 22,
        Publisher = 23,
        SampleRate = 24,
        Title = 25,
        TrackGain = 26,
        TrackNumber = 27,
        TrackPeak = 28,
        TrackTotal = 29,
        Url = 30,
        BitDepth = 31,
        Codec = 32,
        StatAddingDate = 40,
        StatLastPlayDate = 41,
        StatMark = 42,
        StatPlayCount = 43,
        StatRating = 44,
    }
}